// Archivo: mdpp/web/src/pages/Profile.styles.ts
import type { CSSProperties } from "react";

export const profileStyles: { [key: string]: CSSProperties } = {
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    minHeight: "100vh",
    backgroundColor: "#f4f4f4",
    fontFamily: "Arial, sans-serif",
  },
  title: {
    fontSize: "1.6rem",
    fontWeight: "bold",
    marginBottom: "1rem",
    color: "#333",
    textAlign: "center",
  },
  usernameHighlight: {
    color: "#1976d2",
  },
  tableWrapper: {
    width: "95%",
    maxWidth: "1200px",
    marginBottom: "2rem",
    borderRadius: "8px",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
    backgroundColor: "#fff",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "0.9rem",
  },
  th: {
    padding: "0.5rem",
    backgroundColor: "#1976d2",
    color: "#fff",
    textAlign: "left",
  },
  td: {
    padding: "0.5rem",
    borderBottom: "1px solid #ddd",
  },
  rowHover: {
    cursor: "pointer",
  },
  blockedRow: {
    backgroundColor: "#ffe6e6",
  },
  filterRow: {
    width: "95%",
    maxWidth: "1200px",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "1rem",
    alignItems: "center",
  },
  filterGroup: {
    display: "flex",
    gap: "0.5rem",
    alignItems: "center",
  },
  filterButton: {
    padding: "0.5rem 1rem",
    fontSize: "0.9rem",
    borderRadius: "4px",
    border: "1px solid #1976d2",
    backgroundColor: "#1976d2",
    color: "#fff",
    cursor: "pointer",
  },
  filterButtonSecondary: {
    padding: "0.5rem 1rem",
    fontSize: "0.9rem",
    borderRadius: "4px",
    border: "1px solid #ccc",
    backgroundColor: "#fff",
    color: "#333",
    cursor: "pointer",
  },
  selectionInfo: {
    fontSize: "0.9rem",
    color: "#555",
  },
  dangerButton: {
    padding: "0.5rem 1rem",
    fontSize: "0.9rem",
    borderRadius: "4px",
    border: "1px solid #b71c1c",
    backgroundColor: "#b71c1c",
    color: "#fff",
    cursor: "pointer",
  },
  blockButton: {
    padding: "0.5rem 1rem",
    fontSize: "0.9rem",
    borderRadius: "4px",
    border: "1px solid #d32f2f",
    backgroundColor: "#d32f2f",
    color: "#fff",
    cursor: "pointer",
  },
  unblockButton: {
    padding: "0.5rem 1rem",
    fontSize: "0.9rem",
    borderRadius: "4px",
    border: "1px solid #388e3c",
    backgroundColor: "#388e3c",
    color: "#fff",
    cursor: "pointer",
  },
  secondaryButton: {
    padding: "0.5rem 1rem",
    fontSize: "0.9rem",
    borderRadius: "4px",
    border: "1px solid #1976d2",
    backgroundColor: "#fff",
    color: "#1976d2",
    cursor: "pointer",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  modalContent: {
    backgroundColor: "#fff",
    padding: "1.5rem",
    borderRadius: "8px",
    width: "90%",
    maxWidth: "900px",
    maxHeight: "90vh",
    overflowY: "auto",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1rem",
  },
  modalTitle: {
    fontSize: "1.2rem",
    fontWeight: "bold",
  },
  closeButton: {
    background: "none",
    border: "none",
    fontSize: "1.2rem",
    cursor: "pointer",
  },

  // --- Estilos hoja de vida / CV para el modal de usuario ---
  detailsContainer: {
    maxWidth: "720px",
    margin: "0 auto",
    background: "linear-gradient(135deg,#f9fafb,#eef2ff)",
    borderRadius: 16,
    padding: "18px 20px 20px",
    border: "1px solid #e5e7eb",
    boxShadow: "0 10px 25px rgba(15,23,42,0.12)",
    boxSizing: "border-box",
  },
  detailsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "1rem",
    marginBottom: "1rem",
    borderBottom: "1px solid #e5e7eb",
    paddingBottom: "0.75rem",
  },
  detailsHeaderName: {
    fontSize: "1.05rem",
    fontWeight: 700,
    color: "#111827",
    marginBottom: "0.2rem",
  },
  detailsHeaderTag: {
    fontSize: "0.8rem",
    color: "#4b5563",
  },
  detailsHeaderChip: {
    padding: "3px 9px",
    borderRadius: 999,
    fontSize: "0.7rem",
    backgroundColor: "#e0f2fe",
    color: "#0369a1",
    fontWeight: 500,
    border: "1px solid #bae6fd",
    whiteSpace: "nowrap",
  },
  detailsBody: {
    display: "flex",
    gap: "1.25rem",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  detailsLeft: {
    flex: 1,
    minWidth: "230px",
  },
  detailsSection: {
    marginBottom: "0.75rem",
  },
  detailsSectionTitle: {
    fontSize: "0.8rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: "#6b7280",
    marginBottom: "0.35rem",
  },
  detailsRow: {
    display: "flex",
    gap: "0.35rem",
    marginBottom: "0.2rem",
    fontSize: "0.82rem",
    color: "#374151",
  },
  detailsLabel: {
    minWidth: "110px",
    fontWeight: 600,
    color: "#4b5563",
  },
  detailsPhotoWrapper: {
    width: "150px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.45rem",
  },
  detailsAvatar: {
    width: "110px",
    height: "110px",
    borderRadius: "50%",
    objectFit: "cover",
    border: "2px solid #2563eb",
    boxShadow: "0 4px 10px rgba(37,99,235,0.35)",
    backgroundColor: "#e5e7eb",
  },
  detailsAvatarPlaceholder: {
    width: "110px",
    height: "110px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px dashed #9ca3af",
    color: "#6b7280",
    fontSize: "0.75rem",
    backgroundColor: "#f9fafb",
  },
  detailsPhotoLabel: {
    fontSize: "0.78rem",
    color: "#4b5563",
    textAlign: "center",
  },

  tabsContainer: {
    display: "flex",
    marginBottom: "1rem",
    borderBottom: "1px solid #ddd",
  },
  tabButton: {
    padding: "0.5rem 1rem",
    cursor: "pointer",
    border: "none",
    borderBottom: "2px solid transparent",
    backgroundColor: "transparent",
    fontWeight: "bold",
  },
  tabButtonActive: {
    borderBottom: "2px solid #1976d2",
    color: "#1976d2",
  },
  partesList: {
    maxHeight: "300px",
    overflowY: "auto",
    border: "1px solid #ddd",
    borderRadius: "4px",
    padding: "0.5rem",
  },
  parteItem: {
    padding: "0.5rem",
    borderBottom: "1px solid #eee",
    cursor: "pointer",
  },
  parteItemHover: {
    backgroundColor: "#f5f5f5",
  },
  bloqueadoLabel: {
    color: "#d32f2f",
    fontWeight: "bold",
    marginLeft: "0.5rem",
  },
  multimediaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    gap: "0.75rem",
    marginTop: "1rem",
  },
  multimediaItem: {
    borderRadius: "4px",
    overflow: "hidden",
    border: "1px solid #ddd",
    padding: "0.25rem",
    backgroundColor: "#fafafa",
  },
  multimediaImage: {
    width: "100%",
    height: "auto",
    borderRadius: "4px",
  },
  multimediaVideo: {
    width: "100%",
    height: "auto",
    borderRadius: "4px",
  },
  multimediaName: {
    fontSize: "0.8rem",
    marginTop: "0.25rem",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
  },
  modalButtonsRow: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: "1rem",
    gap: "0.5rem",
  },
};
